# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-08 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('allweight', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('allprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('privilege', models.CharField(max_length=100)),
                ('mustbuy', models.BooleanField(default=False, verbose_name='必买')),
                ('goodsimg', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sfyx_goods',
            },
        ),
        migrations.CreateModel(
            name='Goodstype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Goodstype')),
            ],
            options={
                'db_table': 'sfyx_goodstype',
            },
        ),
        migrations.CreateModel(
            name='Lubo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgaddr', models.CharField(max_length=200)),
                ('imgtype', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sfyx_lubo',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goodstype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Goodstype'),
        ),
    ]
