# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-10 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191008_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='storenums',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
