# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-10 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='用户手机号')),
                ('order_code', models.CharField(max_length=100, verbose_name='订单编号')),
                ('total_count', models.IntegerField(verbose_name='订单总数量')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='订单总金额')),
                ('status', models.SmallIntegerField(verbose_name='1未支付，2未发货，3未收货')),
            ],
            options={
                'db_table': 'sfyx_order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='用户手机号')),
                ('order_code', models.CharField(max_length=100, verbose_name='订单编号')),
                ('goods_id', models.IntegerField(verbose_name='商品id')),
                ('counts', models.IntegerField(verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='商品单价')),
            ],
            options={
                'db_table': 'sfyx_order_detail',
            },
        ),
    ]
