# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='商品单价'),
        ),
    ]
